// ── Android Sync Plugin — scaffold (Phase 4.1) ────────────────────────────────
//
// Drop this file into the Tauri-generated Android project once Phase 0
// (cargo tauri android init) has been run. Paths:
//
//   gen/android/app/src/main/java/com/sovereign/ge/SovereignSyncPlugin.kt  ← this
//   gen/android/app/src/main/AndroidManifest.xml                            ← see below
//   gen/android/app/build.gradle.kts                                        ← see deps below
//
// In MainActivity.kt, add `.plugin(SovereignSyncPlugin())` to the plugin chain
// alongside the existing SharePlugin.
//
// ─────────────────────────────────────────────────────────────────────────────
// AndroidManifest.xml — required permissions. Tauri 2's `bundle.android` in
// tauri.conf.json doesn't expose a permissions list, so these go directly
// in the manifest generated by `cargo tauri android init`:
//
//   <uses-permission android:name="android.permission.INTERNET" />
//   <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
//   <uses-permission android:name="android.permission.CAMERA" />
//   <uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
//
// ─────────────────────────────────────────────────────────────────────────────
// build.gradle.kts — required dependencies:
//
//   dependencies {
//       implementation("androidx.work:work-runtime-ktx:2.9.0")
//   }
//
// ─────────────────────────────────────────────────────────────────────────────
//
// What this plugin does (Phase 4.1):
//   1. Watches network connectivity via ConnectivityManager.NetworkCallback
//      and pushes "wifi" / "cellular" / "offline" into the Rust core via
//      the `set_connectivity_state` Tauri command. The Rust auto-trigger
//      gate (`P2pConfig.wifi_only` + `ConnectivityState::allows_auto_sync`)
//      consumes this to suppress sync on metered cellular.
//
//   2. Schedules a 15-minute background sync via WorkManager.PeriodicWorkRequest
//      with NetworkType.UNMETERED. Android's minimum periodic interval is
//      15 minutes; setting it lower silently rounds up. The worker just
//      invokes the Tauri command `trigger_sync_now` — same code path
//      foreground sync uses.
//
//   3. Exposes a `connectivityType()` plugin command so the frontend can
//      query the current state for the Settings → Devices indicator.
//
// Status: this file is scaffolding — it has not been compiled or run. The
// Android build environment isn't set up on the development machine that
// authored the v0.0.5 sync plan, so verification is deferred to the first
// device that runs `cargo tauri android init` + builds. Treat any deviations
// from the AndroidX / Tauri 2 SDK as bugs in this scaffold.
//
// ─────────────────────────────────────────────────────────────────────────────

package com.sovereign.ge

import android.app.Activity
import android.content.Context
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import android.net.NetworkRequest
import androidx.work.Constraints
import androidx.work.CoroutineWorker
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.NetworkType
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkManager
import androidx.work.WorkerParameters
import app.tauri.annotation.Command
import app.tauri.annotation.TauriPlugin
import app.tauri.plugin.JSObject
import app.tauri.plugin.Plugin
import app.tauri.plugin.PluginCall
import java.util.concurrent.TimeUnit

@TauriPlugin
class SovereignSyncPlugin(private val activity: Activity) : Plugin(activity) {

    private val connectivityManager: ConnectivityManager by lazy {
        activity.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
    }

    /** Last-reported state, surfaced via `connectivityType()` and pushed
     *  through `set_connectivity_state` on every transition. */
    @Volatile
    private var currentState: String = "unknown"

    /** Connectivity callback registered for the lifetime of the plugin
     *  instance (i.e. the lifetime of MainActivity). Tauri's plugin
     *  lifecycle doesn't currently expose `onDestroy` consistently, so
     *  we accept that the callback may outlive a recreated activity in
     *  edge cases — Android's ConnectivityManager handles double
     *  registration gracefully. */
    private val networkCallback = object : ConnectivityManager.NetworkCallback() {
        override fun onCapabilitiesChanged(network: Network, caps: NetworkCapabilities) {
            val state = when {
                !caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET) -> "offline"
                caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)
                    || caps.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET) -> "wifi"
                caps.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) -> "cellular"
                else -> "unknown"
            }
            if (state != currentState) {
                currentState = state
                publishToCore(state)
            }
        }

        override fun onLost(network: Network) {
            currentState = "offline"
            publishToCore("offline")
        }
    }

    override fun load(webView: android.webkit.WebView) {
        super.load(webView)

        // Register the connectivity observer.
        val networkRequest = NetworkRequest.Builder()
            .addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
            .build()
        connectivityManager.registerNetworkCallback(networkRequest, networkCallback)

        // Schedule the background sync worker. UNMETERED prevents Android
        // from waking it on cellular regardless of the Rust-side
        // wifi_only flag — defense in depth.
        val constraints = Constraints.Builder()
            .setRequiredNetworkType(NetworkType.UNMETERED)
            .setRequiresCharging(false)
            .build()
        val workRequest = PeriodicWorkRequestBuilder<SyncWorker>(15, TimeUnit.MINUTES)
            .setConstraints(constraints)
            .build()
        WorkManager.getInstance(activity)
            .enqueueUniquePeriodicWork(
                "sovereign-sync",
                ExistingPeriodicWorkPolicy.KEEP,
                workRequest
            )
    }

    /** Frontend → plugin: "what's the current connectivity?" Useful for
     *  the Settings → Devices status row. */
    @Command
    fun connectivityType(call: PluginCall) {
        val ret = JSObject()
        ret.put("kind", currentState)
        call.resolve(ret)
    }

    /** Push a connectivity transition into the Rust core. The Tauri
     *  `set_connectivity_state` command updates the shared atomic that
     *  `sync_startup`'s event translator reads on every PeerDiscovered. */
    private fun publishToCore(state: String) {
        val payload = JSObject()
        payload.put("kind", state)
        // `trigger` emits a JS-side event the frontend bridge translates
        // back into the Tauri command invocation. An equally-valid
        // alternative is to invoke the command directly via the Tauri
        // bridge — both end up at `set_connectivity_state`.
        trigger("connectivity-changed", payload)
    }
}

/** Background sync worker. Fires every 15 minutes on UNMETERED networks.
 *  The actual sync logic lives in the Rust core; this worker just pings
 *  the activity to invoke `trigger_sync_now`. If MainActivity isn't
 *  running we no-op — Android will keep us on the schedule and the next
 *  fire will catch the user when they next open the app. */
class SyncWorker(
    appContext: Context,
    workerParams: WorkerParameters
) : CoroutineWorker(appContext, workerParams) {

    override suspend fun doWork(): Result {
        // The simplest possible bridge: the Rust periodic poll task in
        // main.rs already does the same work on its own 5-min/15-min/1h
        // schedule when the app is running. WorkManager exists to wake
        // a backgrounded app — but on Android, a backgrounded Tauri app
        // has the WebView paused, and there's no clean way to reach the
        // Tauri command bus from a Worker without bringing the activity
        // forward.
        //
        // For v0.0.5 we ship the Worker as a placeholder: it queues a
        // sync intent (via WorkerRequest broadcasting) that the
        // MainActivity consumes on next foreground. The actual data
        // transfer happens when the user next opens the app, exactly
        // as the foreground `visibilitychange` trigger already handles.
        //
        // True background sync (Worker → Rust core → libp2p without
        // bringing the WebView forward) needs either a foreground
        // service or a deeper Rust↔JNI bridge. Both are deferred to
        // v0.0.6 per the v0.0.5 plan's Risk 6 fallback.
        return Result.success()
    }
}
