use std::sync::{Arc, Mutex};

use sovereign_core::config::AppConfig;
use sovereign_core::interfaces::OrchestratorEvent;
use sovereign_core::security::ActionDecision;
use sovereign_core::interfaces::FeedbackEvent;
use sovereign_db::layered::LayeredGraphDB;

/// Runtime model assignment (router + reasoning filenames).
pub struct ModelAssignments {
    pub router: String,
    pub reasoning: String,
}

/// Shared application state managed by Tauri.
///
/// All Tauri commands receive an immutable reference to this via
/// `tauri::State<'_, AppState>`. Interior mutability is handled by
/// Arc + Mutex on the individual subsystems.
pub struct AppState {
    /// `LayeredGraphDB` indirection so the DB can be swapped from raw
    /// `SurrealGraphDB` to `EncryptedGraphDB` at login. Trait calls go through
    /// the current inner via an atomic Arc swap; consumers don't observe the
    /// transition. See `crates/sovereign-db/src/layered.rs`.
    pub db: Arc<LayeredGraphDB>,
    pub orchestrator: Option<Arc<sovereign_ai::Orchestrator>>,
    pub config: AppConfig,
    pub skill_registry: Arc<sovereign_skills::SkillRegistry>,
    pub skill_db: Arc<dyn sovereign_skills::SkillDbAccess>,
    /// LLM access for skills that declare `Capability::LlmInference`.
    /// `None` when the orchestrator failed to initialize (model load error).
    pub skill_llm: Option<Arc<dyn sovereign_skills::SkillLlmAccess>>,
    pub decision_tx: tokio::sync::mpsc::Sender<ActionDecision>,
    pub feedback_tx: tokio::sync::mpsc::Sender<FeedbackEvent>,
    /// Sender end for orchestrator events (for forwarding to Tauri events).
    pub orch_tx: std::sync::mpsc::Sender<OrchestratorEvent>,
    /// Current UI theme ("dark" or "light").
    pub theme: Mutex<String>,
    /// Auto-commit engine for document edits.
    pub autocommit: Arc<tokio::sync::Mutex<sovereign_ai::AutoCommitEngine>>,
    /// Current model assignments (router + reasoning filenames).
    pub model_assignments: Mutex<ModelAssignments>,
    /// User profile directory path (~/.sovereign).
    pub profile_dir: std::path::PathBuf,
    /// User-scoped key for PII vault, body_raw, and session-log encryption.
    /// None until the user completes onboarding or logs in (post-login the
    /// lock holds Some). Same value on every paired device, so encrypted
    /// at-rest data is portable across the user's devices.
    ///
    /// Wrapped in tokio::sync::RwLock so it can be installed by Tauri
    /// commands (validate_password, complete_onboarding) after AppState
    /// is constructed. Reads return a snapshot Arc clone so the guard
    /// is dropped immediately.
    #[cfg(feature = "encryption")]
    pub account_key: tokio::sync::RwLock<Option<Arc<sovereign_crypto::account_key::AccountKey>>>,
    /// Per-device key used solely for libp2p identity derivation (PeerId).
    /// Different on every device. Installed alongside `account_key` in the
    /// post-authentication flow; consumed by P2P startup.
    #[cfg(feature = "encryption")]
    pub p2p_identity_key: tokio::sync::RwLock<Option<Arc<sovereign_crypto::device_key::DeviceKey>>>,
    /// Pending pairing payload + PIN, generated by `generate_pair_qr` on
    /// the existing device and held until the new device redeems it (or
    /// the TTL expires). Single-use; cleared after a successful consume
    /// on the existing device's side or when a new pairing is generated.
    #[cfg(feature = "encryption")]
    pub pending_pairing:
        tokio::sync::RwLock<Option<(sovereign_crypto::pair_payload::PairPayload, String)>>,
    /// P2P command sender for queueing `StartSync` / `PairDevice` /
    /// `Shutdown` from Tauri commands and the periodic poll task.
    /// `None` until `install_session` runs the post-login P2P startup.
    #[cfg(feature = "p2p")]
    pub p2p_command_tx:
        tokio::sync::RwLock<Option<tokio::sync::mpsc::Sender<sovereign_p2p::P2pCommand>>>,
    /// In-memory paired devices, persisted under
    /// `~/.sovereign/crypto/paired_devices.json`. `None` until
    /// `install_session` loads (or initialises) the manager. Arc-shared
    /// with the sync_startup event translator, which persists the new
    /// device record when the P3.1 handshake emits `PairingCompleted`.
    #[cfg(feature = "p2p")]
    pub pairing_manager:
        Arc<tokio::sync::RwLock<Option<sovereign_p2p::pairing::PairingManager>>>,
    /// Concrete listen multiaddrs the P2P swarm reported (interface-
    /// expanded). Collected by the event translator; pairing offers use
    /// them as dial hints so the new device doesn't depend on mDNS.
    #[cfg(feature = "p2p")]
    pub p2p_listen_addrs: Arc<std::sync::RwLock<Vec<String>>>,
    /// Opt-in backup host store (P4.2): fragments + guardian shards we
    /// hold for other users. `None` until P2P startup, or when
    /// `p2p.backup_host_enabled` is off. Shared with the node.
    #[cfg(feature = "p2p")]
    pub backup_host:
        tokio::sync::RwLock<Option<std::sync::Arc<sovereign_p2p::BackupHost>>>,
    /// Latest connectivity state reported by the Android plugin (Phase
    /// 4.2). Shared with the sync_startup event translator + periodic
    /// poll so they can suppress auto-sync on Cellular/Offline when
    /// `config.p2p.wifi_only` is true. Defaults to `Unknown`; desktop
    /// builds leave it there (wifi_only is false on desktop, so the
    /// gate is permissive).
    #[cfg(feature = "p2p")]
    pub connectivity:
        std::sync::Arc<std::sync::atomic::AtomicU8>,
    /// Whisper STT engine for mobile voice-to-text (Web Audio API → Whisper).
    /// Populated when voice-stt feature is enabled and whisper model exists.
    /// Desktop uses the cpal-based VoicePipeline instead.
    #[cfg(feature = "voice-stt")]
    pub stt_engine: Option<Arc<tokio::sync::Mutex<sovereign_ai::voice::stt::SttEngine>>>,
}

/// IPC-005: data commands may only be invoked from the trusted main
/// webview. The embedded `browser` webview renders arbitrary external
/// pages; even while the session is unlocked it must never reach data
/// commands through the IPC bridge.
pub fn require_main_webview(caller: &tauri::Webview) -> Result<(), String> {
    if caller.label() == "main" {
        Ok(())
    } else {
        Err(format!("Command not available to webview '{}'", caller.label()))
    }
}

// Without the encryption feature there is no login/account-key concept, so
// the session check is a no-op (keeps the ~65 gated commands compiling in
// all feature configurations). The shipped builds always enable encryption.
// The caller (webview) check still applies in every configuration.
#[cfg(not(feature = "encryption"))]
impl AppState {
    pub async fn require_unlocked(&self, caller: &tauri::Webview) -> Result<(), String> {
        require_main_webview(caller)?;
        self.require_session_unlocked().await
    }

    pub async fn require_session_unlocked(&self) -> Result<(), String> {
        Ok(())
    }
}

#[cfg(feature = "encryption")]
impl AppState {
    /// Snapshot the account key. Cheap (one Arc::clone) and the read
    /// guard is dropped before returning, so callers can hold the
    /// result without blocking other readers / writers.
    pub async fn account_key(&self) -> Option<Arc<sovereign_crypto::account_key::AccountKey>> {
        self.account_key.read().await.clone()
    }

    /// Authorization gate for data/IPC commands (IPC-004 + IPC-005).
    /// Rejects unless the caller is the trusted main webview AND a session
    /// is unlocked — i.e. `install_session` has installed the account key
    /// and swapped in the EncryptedGraphDB. Bootstrap commands (onboarding,
    /// auth, theme, connectivity, voice, paired-onboarding) must NOT call
    /// this; every other command must call it first so the plaintext
    /// bootstrap DB is never readable pre-login.
    pub async fn require_unlocked(&self, caller: &tauri::Webview) -> Result<(), String> {
        require_main_webview(caller)?;
        self.require_session_unlocked().await
    }

    /// Caller-agnostic session check (IPC-004 only). For internal callers
    /// with no webview, and for the one command legitimately invoked FROM
    /// the browser webview (`__browser_form_extracted`), which enforces its
    /// own caller restriction instead.
    pub async fn require_session_unlocked(&self) -> Result<(), String> {
        if self.account_key.read().await.is_some() {
            Ok(())
        } else {
            Err("Not authenticated: log in first.".to_string())
        }
    }

    /// Install a freshly-derived account key (called post-authentication).
    pub async fn set_account_key(&self, key: Arc<sovereign_crypto::account_key::AccountKey>) {
        *self.account_key.write().await = Some(key);
    }

    /// Snapshot the per-device libp2p identity key.
    pub async fn p2p_identity_key(&self) -> Option<Arc<sovereign_crypto::device_key::DeviceKey>> {
        self.p2p_identity_key.read().await.clone()
    }

    /// Install the per-device libp2p identity key (called post-authentication).
    pub async fn set_p2p_identity_key(&self, key: Arc<sovereign_crypto::device_key::DeviceKey>) {
        *self.p2p_identity_key.write().await = Some(key);
    }
}

#[cfg(feature = "p2p")]
impl AppState {
    /// Snapshot the P2P command channel. Cheap (one mpsc::Sender clone).
    pub async fn p2p_command_tx(
        &self,
    ) -> Option<tokio::sync::mpsc::Sender<sovereign_p2p::P2pCommand>> {
        self.p2p_command_tx.read().await.clone()
    }

    /// Install the P2P command channel after the post-login node start.
    pub async fn set_p2p_command_tx(
        &self,
        tx: tokio::sync::mpsc::Sender<sovereign_p2p::P2pCommand>,
    ) {
        *self.p2p_command_tx.write().await = Some(tx);
    }

    /// Snapshot the current connectivity state. Lock-free atomic read.
    pub fn connectivity_state(&self) -> sovereign_p2p::ConnectivityState {
        connectivity_from_u8(
            self.connectivity.load(std::sync::atomic::Ordering::Relaxed),
        )
    }

    /// Update the connectivity state. Called by the
    /// `set_connectivity_state` Tauri command, which the Android plugin
    /// invokes on every network transition.
    pub fn set_connectivity_state(&self, state: sovereign_p2p::ConnectivityState) {
        self.connectivity
            .store(connectivity_to_u8(state), std::sync::atomic::Ordering::Relaxed);
    }
}

#[cfg(feature = "p2p")]
fn connectivity_to_u8(state: sovereign_p2p::ConnectivityState) -> u8 {
    use sovereign_p2p::ConnectivityState;
    match state {
        ConnectivityState::Unknown => 0,
        ConnectivityState::Wifi => 1,
        ConnectivityState::Cellular => 2,
        ConnectivityState::Offline => 3,
    }
}

#[cfg(feature = "p2p")]
fn connectivity_from_u8(byte: u8) -> sovereign_p2p::ConnectivityState {
    use sovereign_p2p::ConnectivityState;
    match byte {
        1 => ConnectivityState::Wifi,
        2 => ConnectivityState::Cellular,
        3 => ConnectivityState::Offline,
        _ => ConnectivityState::Unknown,
    }
}
